name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: "1.0.10"
    # fix poetry to use python3
    # poetry's python detection has been broken by design for years.
    # It's unlikely that this will be fixed anytime soon.
    # see https://github.com/python-poetry/poetry/issues/721
    # and related issues.
    - name: fix poetry
      run: sed --in-place 's;^#!/usr/bin/env python$;#!/usr/bin/env python3;' $(which poetry)
    - name: check pip version
      run: python3 -m pip --version
    - name: update pip version
      run: python3 -m pip install -v -U pip
    - name: install setuptools
      run: sudo apt install python3-setuptools
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Interactive debug
      uses: mxschmitt/action-tmate@v2
      if: failure() && github.event_name == 'workflow_dispatch'
    - name: Print pip log
      run: cat $(cargo run path bin)/../pip.log
      if: cancelled()
