name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: "1.0.10"
    - name: check pip version
      run: python3 -m pip --version
    - name: update pip version
      run: python3 -m pip install -v -U pip
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
