name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          version: 1.6.1
      - name: try poetry
        run: poetry --version
      - name: install poetry plugin
        run: |
          cd poetry_plugin_virtpy
          poetry build
          POETRY_PYTHON=$(head -n 1 $(which poetry) | cut -c 3-)
          $POETRY_PYTHON -m pip install dist/poetry_plugin_virtpy-*.whl
      - name: check pip version
        run: python3 -m pip --version
      - name: ensure up-to-date packaging tools
        run: python3 -m pip install -v -U pip wheel
      - name: install setuptools
        run: sudo apt install python3-setuptools
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Interactive debug
        uses: mxschmitt/action-tmate@v3
        if: failure() && github.event_name == 'workflow_dispatch'
      - name: Print pip log
        run: cat $(cargo run path bin)/../pip.log
        if: cancelled()
